"use client";

import styles from "./reports.module.css";
import React, { useState, useEffect } from "react";
import ModalPortal from "@/app/components/ModalPortal";

export default function ReportsPage() {
    const [isGenerating, setIsGenerating] = useState(false);
    const [selectedReport, setSelectedReport] = useState<any>(null);
    const [history, setHistory] = useState<any[]>([]);

    const reportTemplates = [
        {
            id: 1,
            title: "Financial Audit",
            description: "Complete breakdown of revenue, expenses, and profit margins across all sectors.",
            icon: (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="1" x2="12" y2="23"></line><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>
            ),
            color: "#E8F9F1",
            text: "#34D186"
        },
        {
            id: 2,
            title: "Agent Efficiency",
            description: "Performance metrics for autonomous agents, including task completion rates and idle time.",
            icon: (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M22 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
            ),
            color: "#E8F0FE",
            text: "#4285F4"
        },
        {
            id: 3,
            title: "Workflow Throughput",
            description: "Analysis of loop executions, bottleneck detection, and autonomous throughput optimization.",
            icon: (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline></svg>
            ),
            color: "#FFF5E8",
            text: "#FFB038"
        }
    ];

    useEffect(() => {
        fetchReports();
    }, []);

    const fetchReports = async () => {
        try {
            const response = await fetch('/api/reports');
            const data = await response.json();
            if (Array.isArray(data)) {
                setHistory(data);
            }
        } catch (error) {
            console.error('Error fetching reports:', error);
        }
    };

    const generateReport = async (templateName: string) => {
        setIsGenerating(true);
        try {
            const reportData = {
                name: `${templateName} - ${new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' })}`,
                type: templateName.split(' ')[0],
                date: new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }),
                size: `${(Math.random() * 5 + 1).toFixed(1)} MB`,
                content: `This is a comprehensive ${templateName} generated by the BLONK autonomous engine. It analyzes historical loop performance and financial throughput for the current operation.`
            };

            const response = await fetch('/api/reports', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(reportData)
            });

            if (response.ok) {
                const newReport = await response.json();
                setHistory(prev => [newReport, ...prev]);
            }
        } catch (error) {
            console.error('Error generating report:', error);
        } finally {
            setIsGenerating(false);
        }
    };

    const exportHref = "/api/reports/export";

    return (
        <div className={styles.reportsContainer}>
            <div className={styles.header}>
                <div className={styles.headerTitle}>
                    <h1>Reports & Analytics</h1>
                    <p>Generate and manage detailed oversight documents for your autonomous firm.</p>
                </div>
                <div className={styles.headerActions}>
                    <a className={styles.btnOutline as unknown as string} href={exportHref}>
                        Export All
                    </a>
                    <button
                        className={styles.btnPrimary}
                        onClick={() => generateReport("Quick Audit")}
                        disabled={isGenerating}
                    >
                        {isGenerating ? <div className={styles.loader} /> : "+ Generate New Report"}
                    </button>
                </div>
            </div>

            <div className={styles.reportsGrid}>
                {reportTemplates.map((template) => (
                    <div key={template.id} className={styles.reportCard}>
                        <div className={styles.cardIcon} style={{ background: template.color, color: template.text }}>
                            {template.icon}
                        </div>
                        <div className={styles.cardContent}>
                            <h3>{template.title}</h3>
                            <p>{template.description}</p>
                        </div>
                        <div className={styles.cardFooter}>
                            <span className={styles.lastGenerated}>Updated 2d ago</span>
                            <button
                                className={styles.actionBtn}
                                onClick={() => generateReport(template.title)}
                                disabled={isGenerating}
                            >
                                Use Template
                            </button>
                        </div>
                    </div>
                ))}
            </div>

            <div className={styles.historySection}>
                <h2 className={styles.sectionTitle}>Recent Generations</h2>
                <table className={styles.historyTable}>
                    <thead>
                        <tr>
                            <th>Report Name</th>
                            <th>Type</th>
                            <th>Date</th>
                            <th>Size</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {history.map((report, i) => (
                            <tr key={i}>
                                <td>
                                    <div className={styles.reportName}>
                                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#949A97" strokeWidth="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline></svg>
                                        <strong>{report.name}</strong>
                                    </div>
                                </td>
                                <td>{report.type}</td>
                                <td>{report.date}</td>
                                <td>{report.size}</td>
                                <td><span className={`${styles.statusPill} ${styles.statusReady}`}>{report.status}</span></td>
                                <td className={styles.rowActions}>
                                    <button className={styles.rowActionBtn} onClick={() => setSelectedReport(report)}>View</button>
                                    <a className={styles.rowActionBtn as unknown as string} href={`/api/reports/download?id=${encodeURIComponent(report.id)}`}>
                                        Download
                                    </a>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {selectedReport && (
                <ModalPortal>
                    <div className={styles.modalOverlay} onClick={() => setSelectedReport(null)} style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(15, 23, 42, 0.4)', backdropFilter: 'blur(12px)', zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                        <div className={styles.modal} onClick={e => e.stopPropagation()}>
                            <div className={styles.modalHeader}>
                                <h2>{selectedReport.name}</h2>
                                <button className={styles.closeBtn} onClick={() => setSelectedReport(null)}>&times;</button>
                            </div>
                            <div className={styles.modalContent}>
                                <div className={styles.reportMeta}>
                                    <span><strong>Type:</strong> {selectedReport.type}</span>
                                    <span><strong>Date:</strong> {selectedReport.date}</span>
                                    <span><strong>Size:</strong> {selectedReport.size}</span>
                                </div>
                                <div className={styles.reportData}>
                                    <h3>Operational Metrics Summary</h3>
                                    <p>{selectedReport.content}</p>

                                    <div className={styles.summaryBox}>
                                        <div>
                                            <span>Total Loops</span>
                                            <strong>1,248,390</strong>
                                        </div>
                                        <div>
                                            <span>Success Rate</span>
                                            <strong>99.4%</strong>
                                        </div>
                                        <div>
                                            <span>Efficiency Gain</span>
                                            <strong>+12%</strong>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className={styles.modalFooter}>
                                <button className={styles.btnOutline} onClick={() => setSelectedReport(null)}>Close</button>
                                <a className={styles.btnPrimary as unknown as string} href={`/api/reports/download?id=${encodeURIComponent(selectedReport.id)}`}>
                                    Download TXT
                                </a>
                            </div>
                        </div>
                    </div>
                </ModalPortal>
            )}
        </div>
    );
}
